// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
// Original file comments:
// Copyright 2017, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Api.MessageBroker.Grpc {
  public static partial class svcMessageService
  {
    static readonly string __ServiceName = "Api.MessageBroker.Grpc.svcMessageService";

    static readonly grpc::Marshaller<global::Api.MessageBroker.Grpc.mMessage> __Marshaller_Api_MessageBroker_Grpc_mMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Api.MessageBroker.Grpc.mMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Api.MessageBroker.Grpc.mMessageFromServer> __Marshaller_Api_MessageBroker_Grpc_mMessageFromServer = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Api.MessageBroker.Grpc.mMessageFromServer.Parser.ParseFrom);

    static readonly grpc::Method<global::Api.MessageBroker.Grpc.mMessage, global::Api.MessageBroker.Grpc.mMessageFromServer> __Method_sendMsg = new grpc::Method<global::Api.MessageBroker.Grpc.mMessage, global::Api.MessageBroker.Grpc.mMessageFromServer>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "sendMsg",
        __Marshaller_Api_MessageBroker_Grpc_mMessage,
        __Marshaller_Api_MessageBroker_Grpc_mMessageFromServer);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Api.MessageBroker.Grpc.MessageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of svcMessageService</summary>
    public abstract partial class svcMessageServiceBase
    {
      public virtual global::System.Threading.Tasks.Task sendMsg(grpc::IAsyncStreamReader<global::Api.MessageBroker.Grpc.mMessage> requestStream, grpc::IServerStreamWriter<global::Api.MessageBroker.Grpc.mMessageFromServer> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for svcMessageService</summary>
    public partial class svcMessageServiceClient : grpc::ClientBase<svcMessageServiceClient>
    {
      /// <summary>Creates a new client for svcMessageService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public svcMessageServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for svcMessageService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public svcMessageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected svcMessageServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected svcMessageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Api.MessageBroker.Grpc.mMessage, global::Api.MessageBroker.Grpc.mMessageFromServer> sendMsg(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return sendMsg(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Api.MessageBroker.Grpc.mMessage, global::Api.MessageBroker.Grpc.mMessageFromServer> sendMsg(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_sendMsg, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override svcMessageServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new svcMessageServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(svcMessageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_sendMsg, serviceImpl.sendMsg).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, svcMessageServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_sendMsg, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Api.MessageBroker.Grpc.mMessage, global::Api.MessageBroker.Grpc.mMessageFromServer>(serviceImpl.sendMsg));
    }

  }
}
#endregion
